### PR TITLE
use keystore

### PR DESCRIPTION
**Pull request by evollu**
inspired by https://medium.com/@ericfu/securely-storing-secrets-in-an-android-application-501f030ae5a3#.v6x38hycm

- min required version changed to 18 because keystore is only available 18+
- added promise callback for set item

### CODE REVIEW

**Comment by mCodex** [comment]
Hello @evollu , thank you!!!! 😃 I'll merge it, also I'd like to know if you can provide some example to put it into README?

**Comment by evollu** [comment]
there is no change is usage. It encrypts every value in the shared preference.

**Comment by mCodex** [comment]
@evollu , thank you for your response. Sorry, i didn't know that.

**Comment by evollu** [comment]
@mCodex I just realized that this is a breaking change. Old values stored in shared preference won't be readable.

**Comment by vspedr** [comment]
Hi @evollu, thanks for your response!
We had already merged your PR but did not release it on npm so it should not affect others. We decided to revert it for now, but in case you find a new fix feel free to submit another PR ;)

**Comment by evollu** [comment]
because the backward compatibility?

**Comment by vspedr** [comment]
Yes, we're planning a new major release, just need to get everything in place so we don't accidentally break stuff for people who already use this module

**Pull request merged**
